DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS Polls CASCADE;
DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS submission CASCADE;



CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(350) NOT NULL,
  poll_link VARCHAR(350) NOT NULL,
  results_link VARCHAR(350) NOT NULL
);

CREATE TABLE results (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  choice VARCHAR(350) NOT NULL,
  rating INTEGER  NOT NULL DEFAULT 0
);


CREATE TABLE submission (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  activity VARCHAR(350) NOT NULL,
  rating INTEGER  NOT NULL DEFAULT 0
);